### ISSUE TITLE
hlhlhl -> ㅚㅗㅣㅗㅣ로 변환함

### ISSUE THREAD

**Issue by algoshipda** [JonJee/inko#12]
hlhlhl -> ㅚㅗㅣㅗㅣ로 변환함

**Comment by JonJee** [comment]
@algoshipda 버그리포트 감사합니다.

**Comment by algoshipda** [comment]
#13

**Comment by JonJee** [comment]
@algoshipda rtrt이 ㄱㅅㄱㅅ이 맞을까요?? ㄳㄳ이 맞을까요??

**Comment by algoshipda** [comment]
정확히 뭐에 의해 결정되는지 모르겠지만,
결정하는 방식을 옵션으로 받아야하지 않을까요?

**Comment by JonJee** [comment]
@algoshipda 그러는게 좋겠네요!
